# Generated by Django 3.2 on 2021-08-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='identity_id',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
