# Generated by Django 3.2 on 2021-08-27 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citizen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthInsurance',
            fields=[
                ('id', models.CharField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('licensing_authorities', models.CharField(max_length=100)),
                ('expiry_date', models.CharField(max_length=200, null=True)),
                ('picture', models.ImageField(upload_to='')),
                ('mi5cy_date', models.DateField()),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='qrcode')),
            ],
        ),
        migrations.CreateModel(
            name='HealthInsuranceCardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KCD_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=256)),
                ('license_id', models.IntegerField()),
                ('license_date', models.IntegerField()),
                ('status', models.CharField(choices=[('Đang hoạt động', 'Đang hoạt động'), ('Ngừng hoạt động', 'Ngừng hoạt động')], max_length=20)),
                ('type', models.CharField(max_length=256)),
                ('head_certificate', models.IntegerField()),
                ('x_pos', models.FloatField()),
                ('y_pos', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RegimeBenefitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percent', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RegimeBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health_insurance.healthinsurancecardtype')),
                ('regime_benefit_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health_insurance.regimebenefittype')),
            ],
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=1024)),
                ('diagnose', models.CharField(max_length=1024)),
                ('treatment', models.CharField(max_length=1024)),
                ('doctor', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=1024)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('re_examination', models.DateTimeField(null=True)),
                ('organ_donor', models.IntegerField(null=True)),
                ('emergency', models.BooleanField()),
                ('appropriate_levels', models.BooleanField()),
                ('health_insurance_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health_insurance.healthinsurance')),
                ('hospital_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_insurance_hospital', to='health_insurance.hospital')),
                ('referral', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_insurance_referral', to='health_insurance.hospital')),
            ],
            options={
                'ordering': ('-end_date',),
            },
        ),
        migrations.AddField(
            model_name='healthinsurance',
            name='card_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health_insurance.healthinsurancecardtype'),
        ),
        migrations.AddField(
            model_name='healthinsurance',
            name='hospital_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health_insurance.hospital'),
        ),
        migrations.AddField(
            model_name='healthinsurance',
            name='identity_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='citizen.citizen'),
        ),
    ]
