# Generated by Django 3.2 on 2021-08-28 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0002_auto_20210828_1010'),
        ('health_insurance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthinsurance',
            name='health_insurance_id',
            field=models.CharField(max_length=26, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='healthinsurance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='healthinsurance',
            name='identity_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='citizen.citizen', unique=True),
        ),
    ]
