# Generated by Django 3.2 on 2021-08-28 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_insurance', '0002_auto_20210828_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthinsurance',
            name='qrcode',
        ),
        migrations.AddField(
            model_name='healthinsurance',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode'),
        ),
    ]
