# Generated by Django 3.2 on 2021-08-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_insurance', '0004_auto_20210828_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='head_certificate',
            field=models.CharField(max_length=20),
        ),
    ]
