# Generated by Django 3.2.6 on 2021-08-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_insurance', '0007_auto_20210828_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='central_line',
            field=models.BooleanField(default=False),
        ),
    ]
