# Generated by Django 3.2 on 2021-08-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_insurance', '0008_hospital_central_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='image',
            field=models.ImageField(null=True, upload_to='static/hospital'),
        ),
    ]
