# Generated by Django 3.2 on 2021-08-21 08:52

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=128, validators=[user.validators.validate_secure_password], verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=50, unique=True, validators=[user.validators.validate_phone_number]),
        ),
    ]
